export const actionTypes = {
    GET_BANNER_MOVIE: 'GET_BANNER_MOVIE',
    GET_SELECTED_MOVIE: 'GET_SELECTED_MOVIE',
    GET_MOVIE_PLAYER: 'GET_MOVIE_PLAYER',
    GET_MOVIE_MODAL_OPEN: 'SET_MODAL_OPEN',
    SET_API_REQUEST: 'SET_API_REQUEST',
};